# Stage 1: Build the frontend
FROM node:20.14.0

# Set working directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY ./package*.json ./

# Install dependencies
RUN npm install

# Copy all files
COPY ./ ./

# Build the application
RUN npm run build

# Expose the port Vite uses
EXPOSE 5173

# Set the default command
CMD ["npm", "run", "dev"]
